global:
  scrape_interval: 5s
  external_labels:
    cluster: cv-library
    namespace: poc

rule_files:
  - /etc/prometheus/rules.yaml

scrape_configs:
  - job_name: cv-library/microservices
    static_configs:
      - targets: ['application-cv-library:8000']
        labels:
          container: 'application-cv-library'
      - targets: ['locations-cv-library:8000']
        labels:
          container: 'locations-cv-library'
      - targets: ['candidates-cv-library:8000']
        labels:
          container: 'candidates-cv-library'


remote_write:
  - url: http://load-balancer:9009/api/v1/push
    headers:
      X-Scope-OrgID: cv-library
