{
 "title": "Cron exec exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "query": {
     "query": "label_values(cron_execution,app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "missing per app",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_execution{status=\"missing\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Failed per app",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_execution{status=\"failed\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Success",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (cron_execution{status=\"success\"})",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "SUM by status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (cron_execution{job=\"cv-library/cron_exec_exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron exec exporter Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{container_name=\"poc-cron_exec_exporter-1\"} |= ``"
    }
   ]
  },
  {
   "title": "All Cronjobs",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "cron_execution", "legendFormat": "__auto" }
   ]
  }
 ]
}